In [79]:
import seaborn as sns
import numpy as np
import random
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap


iris = sns.load_dataset('iris')


In [39]:
iris['target'] = iris['species'].replace( iris['species'].unique(), [0,1,2])
Xls = iris.iloc[:100,:-2].to_numpy()
yls = iris['target'].to_numpy()
yls = yls[:100]
print(Xls[0:5],yls[0:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]] [0 0 0 0 0]


In [42]:
print(len(Xls))

100


In [70]:
class Percentron(object):
    """ Perceptron class
    
    Parametri:
    
    """
    def __init__(self,feautures=0,eta=0.01,n_iter=50):
        self._features = feautures
        self._eta = eta
        self._niter = n_iter
        # public
        self.errors = []
        self.w = np.zeros(feautures)
        self.bias = 0
        
    def fit(self,X,y):
        self.errors = []
        for i in range(self._niter):
            print(f"Iterazione: {i} ",end="")
            errori = 0
            # batch on the entire training set
            for xi,target in zip(X,y):
                output = self.predict(xi)     # what do you compute?
                gradient = target - output           # gradient = (target == output)
                update = self._eta * gradient
                self.w += xi * update
                self.bias += update
                errori += int(update != 0.0)
            self.errors.append(errori)
            print(f"Numero errori = {errori}")
            if errori == 0:
                break
    
    def net_input(self,X):
        return X @ self.w + self.bias 
    
    def predict(self,X):
        return np.where(self.net_input(X) > 0.0, 1, 0)


In [44]:
index = random.sample(range(100),60)

[69, 8, 96, 38, 46, 35, 58, 16, 13, 11, 53, 9, 34, 56, 68, 22, 59, 41, 80, 81, 5, 87, 74, 42, 86, 0, 10, 54, 88, 32, 93, 21, 97, 99, 33, 83, 85, 90, 7, 27, 92, 71, 66, 45, 6, 14, 55, 82, 12, 24, 78, 18, 77, 3, 91, 19, 76, 89, 63, 39]


In [54]:
X_train,y_train = Xls[index],yls[index]
mask = np.ones(100,dtype=bool)
mask[index] = False
X_test,y_test = Xls[mask],yls[mask]


In [72]:
neuron = Percentron(4,eta=0.1,n_iter=10)

In [73]:
neuron.fit(X_train,y_train)

Iterazione: 0 Numero errori = 1
Iterazione: 1 Numero errori = 3
Iterazione: 2 Numero errori = 2
Iterazione: 3 Numero errori = 2
Iterazione: 4 Numero errori = 2
Iterazione: 5 Numero errori = 1
Iterazione: 6 Numero errori = 0


In [74]:
neuron.errors

[1, 3, 2, 2, 2, 1, 0]

In [80]:
def plot_decision_regions(X, y, classifier, resolution=0.06):

    # setup marker generator and color map
    markers = ('x', 'o', '^', 'v')
    colors = ('red', 'blue', 'lightgreen', 'gray', 'cyan')
    cmap = ListedColormap(colors[:len(np.unique(y))])

    # plot the decision surface
    x1_min, x1_max = X[:, 0].min() - 0.5, X[:, 0].max() + 0.5
    x2_min, x2_max = X[:, 1].min() - 0.5, X[:, 1].max() + 0.5
    xx1, xx2 = np.meshgrid(np.arange(x1_min, x1_max, resolution),
                           np.arange(x2_min, x2_max, resolution))
    Z = classifier.predict(np.array([xx1.ravel(), xx2.ravel()]).T)
    Z = Z.reshape(xx1.shape)
    plt.contourf(xx1, xx2, Z, alpha=0.2, cmap=cmap)
    plt.xlim(xx1.min(), xx1.max())
    plt.ylim(xx2.min(), xx2.max())

    # plot class examples
    for idx, cl in enumerate(np.unique(y)):
        plt.scatter(x=X[y == cl, 0], 
                    y=X[y == cl, 1],
                    alpha=0.8, 
                    c=colors[idx],
                    marker=markers[idx], 
                    label=cl, 
                    edgecolor='black')

In [81]:
plot_decision_regions(X_train, y_train, classifier=neuron)
plt.xlabel('Pepal length [cm]')
plt.ylabel('Petal length [cm]')
plt.legend(loc='upper left')
# plt.savefig('images/02_08.png', dpi=300)
plt.show()

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 2)