In [1]:
import numpy as np


In [2]:
# creation

a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [82]:
a.shape,a.ndim,a.dtype,a.nbytes

((10,), 1, dtype('float64'), 80)

In [22]:
# more dimension:

b = np.ones((2,3))
print(b)
print("-"*10)

c = np.diag(np.arange(2,5))
print(c)
print("-"*10)

I = np.identity(4)
print(I)
print("-"*10)

d = np.arange(9*2).reshape((3,3,2))
print(d)
print("-"*10)

[[1. 1. 1.]
 [1. 1. 1.]]
----------
[[2 0 0]
 [0 3 0]
 [0 0 4]]
----------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
----------
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
----------


In [21]:
# Selection:
a[1], c[2,2]

(0.0, 4)

In [23]:
np.linspace(-10,10,20)

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

In [114]:
np.r_[-10:10+1:1]

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10])

In [118]:
# selection are VIEW not COPY so mutable

I[1:,1] = np.array([2,1,-1])

In [116]:
I = np.identity(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [119]:
I

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.],
       [ 0.,  1.,  1.,  0.],
       [ 0., -1.,  0.,  1.]])

In [120]:
e = c

In [121]:
print(e)
print(c)

[[2 0 0]
 [0 3 0]
 [0 0 4]]
[[2 0 0]
 [0 3 0]
 [0 0 4]]


In [122]:
print(e[:,0],e[:,0].shape)
e[:,0] = 1

[2 0 0] (3,)


In [123]:
e

array([[1, 0, 0],
       [1, 3, 0],
       [1, 0, 4]])

In [124]:
c

array([[1, 0, 0],
       [1, 3, 0],
       [1, 0, 4]])

In [126]:
c = np.diag(np.arange(2,5))
e = c.copy()
e[:,0] = 1
print(c)
print(e)

[[2 0 0]
 [0 3 0]
 [0 0 4]]
[[1 0 0]
 [1 3 0]
 [1 0 4]]


In [51]:
c.tolist()

[[2, 0, 0], [0, 3, 0], [0, 0, 4]]

In [53]:
a.fill(8)
print(a)

[8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]


In [133]:
x = np.arange(10)

[-1, 0, 2]

In [138]:
# mask for conditional

(x > 4) & (x < 7)

array([False, False, False, False, False,  True,  True, False, False,
       False])

In [139]:
x[ (x > 4) & (x < 7) ]

array([5, 6])

In [140]:
M = np.random.randint(10,100,25).reshape((5,5))
M

array([[70, 64, 59, 73, 10],
       [44, 99, 40, 98, 71],
       [51, 89, 54, 11, 60],
       [65, 46, 96, 48, 73],
       [91, 22, 37, 97, 61]])

In [66]:
M.min(),M.max()

(12, 99)

In [141]:
# compute aggregation over colum

print("Minimums over columns: ",M.min(axis=0))
print("Minimums over rows: ",M.min(axis=1))


Minimums over columns:  [44 22 37 11 10]
Minimums over rows:  [10 40 11 46 22]


In [142]:
M.ravel()

array([70, 64, 59, 73, 10, 44, 99, 40, 98, 71, 51, 89, 54, 11, 60, 65, 46,
       96, 48, 73, 91, 22, 37, 97, 61])

In [81]:
# ufunctions

def f(x):
    return np.exp(-x*x)*np.log(1+x*np.sin(x))

print("f over scalar: ",f(2))
print("f over array: ",f(np.array([1,1.5,2,2.5])))


f over scalar:  0.01897936983747202
f over array:  [0.2246142  0.0964178  0.01897937 0.00176591]


In [144]:
M

array([[70, 64, 59, 73, 10],
       [44, 99, 40, 98, 71],
       [51, 89, 54, 11, 60],
       [65, 46, 96, 48, 73],
       [91, 22, 37, 97, 61]])

In [143]:
M.T

array([[70, 44, 51, 65, 91],
       [64, 99, 89, 46, 22],
       [59, 40, 54, 96, 37],
       [73, 98, 11, 48, 97],
       [10, 71, 60, 73, 61]])

In [88]:
x = np.ones(5)

In [89]:
# np.dot

M @ x

array([226., 218., 284., 280., 280.])

In [90]:
x @ x

5.0

In [91]:
M @ M

array([[14332, 12268, 10444, 10502, 11918],
       [13953,  9834,  8975, 11932, 10568],
       [18646, 10010, 13578, 19961,  8611],
       [20517, 10891, 13034, 16319, 10075],
       [18967, 13806, 11943, 13229, 14447]])

In [92]:
from numpy.linalg import solve


In [93]:
y = solve(M,x)

In [94]:
y

array([ 0.01897273,  0.0741515 , -0.0621668 ,  0.02048107, -0.04375146])

In [148]:
M = np.array([[3,2,-1],[2,0,1],[3,1,2]])
M

array([[ 3,  2, -1],
       [ 2,  0,  1],
       [ 3,  1,  2]])

In [149]:
x = [-1,0,2]

In [150]:
y = solve(M,x)
print(y)

[-0.71428571  1.28571429  1.42857143]


Un interessante applicazione dei sistemi lineari, viene dal modello di
Leontief per la pianificazione della produzione in un modello chiuso.
L'economia è suddivisa in *Settori*, ogni settore produce degli *outputs* e
richiede degli *inputs*. Ha vinto il Nobel per l'economia per questo modello.

In [163]:
# Esempio: settori = agricoltura, manifattura, utility
# produzione in dollari

C = np.array([ [0.5, 0.1, 0.1], [0.2, 0.5, 0.3], [0.1, 0.3, 0.4] ])
print("Technology Matrix\n\n",C)
b = [7900, 3950, 1975]
I = np.identity(3)
A = I-C



Technology Matrix

 [[0.5 0.1 0.1]
 [0.2 0.5 0.3]
 [0.1 0.3 0.4]]


In [151]:
(I-C)x = d

In [164]:
x = solve(A,b)

In [155]:
import scipy.linalg as sl

[LU,piv] = sl.lu_factor(X)

In [158]:
sl.lu_solve((LU,piv),d)

array([27500., 33750., 24750.])

In [166]:
c = A @ x

In [170]:
equal = (b == c).all()
if equal:
    print("Uguali")
else:
    print("Diversi")

Diversi


In [174]:
v1 = np.array([1,2])
v2 = np.array([3,4])
print(np.vstack([v1,v2]))
print(np.column_stack([v1,v2]))
print(np.hstack([v1,v2]))

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3 4]


In [179]:
np.allclose(b,c)

True

In [184]:
x = np.arange(10)
x[ ~(x > 5) | (x == 0) ]

array([0, 1, 2, 3, 4, 5])

In [185]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [186]:
x.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [192]:
print(x.ndim,x.shape)
y = x.T
print(y.ndim,y.shape)

1 (10,)
1 (10,)


In [195]:
x.reshape((10,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [198]:
A = np.array([[1,0,2,0],[0,0,0,0],[3,0,0,0],[1,0,0,4]])
(A > 0).sum()

5